name: release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Release Message
        run: |
          echo "## What's changed?" > release.txt
          git tag -l --sort=-taggerdate --format='%(contents)' $(git describe --tags $(git branch --show-current)) | grep . | while read line; do echo "- $line"; done >> release.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: release.txt
          draft: false
          prerelease: false
          
          # https://stackoverflow.com/questions/65606498/how-to-access-github-tag-message-in-github-actions
          # https://stackoverflow.com/questions/72200924/github-action-prints-commit-message-instead-of-tag-message
          # https://serverfault.com/questions/252921/how-to-remove-empty-blank-lines-from-a-file-in-unix-including-spaces
          # https://serverfault.com/questions/72744/command-to-prepend-string-to-each-line
          # git tag -a 1.0.4 -m "BREAKING: 1" -m "Fix: 2" -m "Feat: 3"
          
          
#      - name: Release Maven package
#        uses: samuelmeuli/action-maven-publish@v1
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
#          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
#          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}

